import AppKit
import Foundation
import OpenComputerUseKit

struct ComputerUseTurnScope: Hashable, Sendable {
    let sessionID: String
    let turnID: String
    let hostSessionID: String?

    init?(metadata: Any?) {
        guard let record = metadata as? [String: Any],
              let sessionID = record["session_id"] as? String,
              !sessionID.isEmpty,
              let turnID = record["turn_id"] as? String,
              !turnID.isEmpty
        else {
            return nil
        }
        self.sessionID = sessionID
        self.turnID = turnID
        self.hostSessionID = record["operon_session_id"] as? String
    }
}

private struct ControlledApp: Sendable {
    let appReference: String
    let bundleIdentifier: String
    let displayName: String
    let appPath: String?
    let pid: pid_t?
    let scope: ComputerUseTurnScope
}

private struct InterventionKey: Hashable {
    let scope: ComputerUseTurnScope
    let bundleIdentifier: String
}

private struct UserIntervention {
    let debounceUntil: Date
}

enum ComputerUseRequestKind {
    case readState
    case performAction
}

func eventTargetsControlledApplication(
    eventType: NSEvent.EventType,
    controlledPID: pid_t?,
    frontmostPID: pid_t?,
    pointerWindowPID: pid_t?
) -> Bool {
    guard let controlledPID else {
        return false
    }

    switch eventType {
    case .keyDown, .flagsChanged:
        return frontmostPID == controlledPID
    case .leftMouseDown,
         .rightMouseDown,
         .otherMouseDown,
         .leftMouseDragged,
         .rightMouseDragged,
         .otherMouseDragged,
         .scrollWheel:
        return pointerWindowPID == controlledPID
    default:
        return false
    }
}

/// Distinguishes explicit stop from physical interaction with the controlled app.
///
/// Input in another app is unrelated to Computer Use and must not interrupt it.
/// Input generated by OpenComputerUseKit carries `ComputerUseSyntheticInputMarker`
/// and is ignored. Physical input targeting the controlled app requests a fresh
/// snapshot; only the menu-bar Stop action ends the current turn.
final class UserInterruptionMonitor: @unchecked Sendable {
    static let shared = UserInterruptionMonitor()

    private static let interactionDebounceDuration: TimeInterval = 1.25

    private let lock = NSLock()
    private var monitorToken: Any?
    private var activeApp: ControlledApp?
    private var stoppedScopes = Set<ComputerUseTurnScope>()
    private var interventions: [InterventionKey: UserIntervention] = [:]
    private var screenLockedOverrideForTesting: Bool?

    private init() {}

    @MainActor
    func start() {
        guard monitorToken == nil else { return }
        let mask: NSEvent.EventTypeMask = [
            .keyDown,
            .flagsChanged,
            .leftMouseDown,
            .rightMouseDown,
            .otherMouseDown,
            .leftMouseDragged,
            .rightMouseDragged,
            .otherMouseDragged,
            .scrollWheel,
        ]
        monitorToken = NSEvent.addGlobalMonitorForEvents(matching: mask) { [weak self] event in
            self?.handlePhysicalEvent(event)
        }
    }

    func beginRequest(
        app: String,
        metadata: Any?,
        kind: ComputerUseRequestKind,
        now: Date = Date()
    ) throws {
        try assertScreenUnlocked()
        guard let scope = ComputerUseTurnScope(metadata: metadata) else {
            return
        }

        let target = try? ComputerUseAppPolicyResolver.resolve(app)
        let bundleIdentifier = target?.bundleIdentifier ?? app
        let runningApplication = NSRunningApplication
            .runningApplications(withBundleIdentifier: bundleIdentifier)
            .first
        let controlledApp = ControlledApp(
            appReference: app,
            bundleIdentifier: bundleIdentifier,
            displayName: target?.displayName ?? bundleIdentifier,
            appPath: target?.appPath,
            pid: runningApplication?.processIdentifier,
            scope: scope
        )
        let key = InterventionKey(scope: scope, bundleIdentifier: bundleIdentifier)
        var pendingError: ComputerUseSessionError?

        lock.lock()
        if activeApp?.scope != scope {
            stoppedScopes = stoppedScopes.filter {
                $0.sessionID != scope.sessionID || $0.turnID == scope.turnID
            }
            interventions = interventions.filter {
                $0.key.scope.sessionID != scope.sessionID || $0.key.scope.turnID == scope.turnID
            }
        }
        activeApp = controlledApp

        if stoppedScopes.contains(scope) {
            pendingError = .stoppedByUser
        } else if let intervention = interventions[key] {
            if now < intervention.debounceUntil {
                let remaining = max(1, Int(ceil(intervention.debounceUntil.timeIntervalSince(now))))
                pendingError = .userIntervened(
                    "The user is still interacting with '\(bundleIdentifier)'. Wait \(remaining) seconds and retry."
                )
            } else if kind == .readState {
                interventions.removeValue(forKey: key)
            } else {
                pendingError = .userIntervened(
                    "The user changed '\(bundleIdentifier)'. Re-query the latest state with `get_app_state` before sending more actions."
                )
            }
        }
        lock.unlock()

        if let pendingError {
            throw pendingError
        }

        activatePresentation(for: controlledApp)
    }

    func stopActiveTurn() {
        var stoppedApp: ControlledApp?
        lock.lock()
        if let activeApp {
            stoppedApp = activeApp
            stoppedScopes.insert(activeApp.scope)
            interventions = interventions.filter { $0.key.scope != activeApp.scope }
            log("user explicitly stopped Computer Use for \(activeApp.bundleIdentifier)")
        }
        lock.unlock()

        if let stoppedApp {
            endPresentation(for: stoppedApp, reason: "stopped")
        }
    }

    func endHostSession(_ hostSessionID: String) {
        var endedApp: ControlledApp?
        lock.lock()
        stoppedScopes = stoppedScopes.filter { $0.hostSessionID != hostSessionID }
        interventions = interventions.filter {
            $0.key.scope.hostSessionID != hostSessionID
        }
        if activeApp?.scope.hostSessionID == hostSessionID {
            endedApp = activeApp
            activeApp = nil
        }
        lock.unlock()

        if let endedApp {
            endPresentation(for: endedApp, reason: "turn-ended")
        }
    }

    private func activatePresentation(for controlledApp: ControlledApp) {
        let update: @MainActor @Sendable () -> Void = {
            ComputerUsePresentationController.shared.activate(
                scope: controlledApp.scope,
                appReference: controlledApp.appReference,
                bundleIdentifier: controlledApp.bundleIdentifier,
                displayName: controlledApp.displayName,
                appPath: controlledApp.appPath
            )
        }
        if Thread.isMainThread {
            MainActor.assumeIsolated(update)
        } else {
            DispatchQueue.main.async(execute: update)
        }
    }

    private func endPresentation(for controlledApp: ControlledApp, reason: String) {
        let update: @MainActor @Sendable () -> Void = {
            ComputerUsePresentationController.shared.end(
                scope: controlledApp.scope,
                reason: reason
            )
        }
        if Thread.isMainThread {
            MainActor.assumeIsolated(update)
        } else {
            DispatchQueue.main.async(execute: update)
        }
    }

    private func handlePhysicalEvent(_ event: NSEvent) {
        if event.cgEvent?.getIntegerValueField(.eventSourceUserData)
            == ComputerUseSyntheticInputMarker.value {
            return
        }

        lock.lock()
        let controlledApp = activeApp
        lock.unlock()
        guard let controlledApp else {
            return
        }

        let frontmostPID = NSWorkspace.shared.frontmostApplication?.processIdentifier
        let pointerWindowPID = event.cgEvent.flatMap { windowOwnerPID(at: $0.location) }
        guard eventTargetsControlledApplication(
            eventType: event.type,
            controlledPID: controlledApp.pid,
            frontmostPID: frontmostPID,
            pointerWindowPID: pointerWindowPID
        ) else {
            return
        }

        recordTargetInteraction(controlledApp: controlledApp, at: Date())
    }

    private func recordTargetInteraction(controlledApp: ControlledApp, at date: Date) {
        let key = InterventionKey(
            scope: controlledApp.scope,
            bundleIdentifier: controlledApp.bundleIdentifier
        )

        lock.lock()
        guard activeApp?.scope == controlledApp.scope,
              activeApp?.bundleIdentifier == controlledApp.bundleIdentifier
        else {
            lock.unlock()
            return
        }
        interventions[key] = UserIntervention(
            debounceUntil: date.addingTimeInterval(Self.interactionDebounceDuration)
        )
        lock.unlock()
        log("user intervened in \(controlledApp.bundleIdentifier); waiting for a fresh state")
    }

    func recordInteractionForTesting(bundleIdentifier: String, at date: Date) {
        lock.lock()
        let controlledApp = activeApp
        lock.unlock()
        guard let controlledApp,
              controlledApp.bundleIdentifier == bundleIdentifier
        else {
            return
        }
        recordTargetInteraction(controlledApp: controlledApp, at: date)
    }

    func resetForTesting() {
        lock.lock()
        activeApp = nil
        stoppedScopes.removeAll()
        interventions.removeAll()
        screenLockedOverrideForTesting = nil
        lock.unlock()
    }

    func setScreenLockedForTesting(_ value: Bool?) {
        lock.lock()
        screenLockedOverrideForTesting = value
        lock.unlock()
    }

    private func assertScreenUnlocked() throws {
        lock.lock()
        let override = screenLockedOverrideForTesting
        lock.unlock()
        if let override {
            if override {
                throw ComputerUseSessionError.screenLocked
            }
            return
        }

        guard let session = CGSessionCopyCurrentDictionary() as? [String: Any] else {
            return
        }
        if session["CGSSessionScreenIsLocked"] as? Bool == true {
            throw ComputerUseSessionError.screenLocked
        }
    }

    private func windowOwnerPID(at point: CGPoint) -> pid_t? {
        guard let infoList = CGWindowListCopyWindowInfo(
            [.optionOnScreenOnly, .excludeDesktopElements],
            kCGNullWindowID
        ) as? [[String: Any]] else {
            return nil
        }

        for info in infoList {
            guard let ownerPID = info[kCGWindowOwnerPID as String] as? pid_t,
                  let boundsDictionary = info[kCGWindowBounds as String] as? NSDictionary,
                  let bounds = CGRect(dictionaryRepresentation: boundsDictionary),
                  bounds.contains(point)
            else {
                continue
            }

            let alpha = (info[kCGWindowAlpha as String] as? NSNumber)?.doubleValue ?? 1
            if alpha > 0 {
                return ownerPID
            }
        }
        return nil
    }

    private func log(_ message: String) {
        FileHandle.standardError.write(Data("[operon-cu] \(message)\n".utf8))
    }
}
