export function Terms() {
  return (
    <div
      style={{
        minHeight: '100vh',
        background: '#000',
        color: '#fff',
        padding: '120px 40px 80px',
      }}
    >
      <div style={{ maxWidth: 720, margin: '0 auto' }}>
        <h1
          style={{
            fontSize: 40,
            fontWeight: 600,
            color: 'rgba(255,255,255,0.92)',
            letterSpacing: '-0.025em',
            marginBottom: 12,
          }}
        >
          Terms of Service
        </h1>
        <p style={{ fontSize: 14, color: 'rgba(255,255,255,0.25)', marginBottom: 48 }}>
          Last updated: March 16, 2026
        </p>

        <Section title="1. Acceptance of Terms">
          By downloading, installing, or using Operon ("the Software"), you agree to be bound by
          these Terms of Service. If you do not agree to these terms, do not use the Software.
        </Section>

        <Section title="2. Description of Service">
          Operon is a desktop application that provides a unified interface for interacting with
          multiple AI coding agents, including Claude Code, Codex, Gemini CLI, OpenCode, and custom
          providers. The Software runs locally on your machine and connects to third-party AI
          services using your own API keys.
        </Section>

        <Section title="3. Your Responsibilities">
          <List items={[
            'You are responsible for obtaining and maintaining valid API keys for any AI providers you wish to use.',
            'You must comply with the terms of service of each AI provider you access through Operon.',
            'You are responsible for all code, content, and actions generated through the Software.',
            'You must not use the Software for any illegal or unauthorized purpose.',
            'You are responsible for reviewing and testing any AI-generated code before deploying it to production.',
          ]} />
        </Section>

        <Section title="4. Third-Party Services">
          Operon integrates with third-party AI services. We are not responsible for the
          availability, accuracy, or reliability of these services. Your use of third-party
          services is subject to their respective terms and conditions.
          <br /><br />
          We do not guarantee that any AI provider will remain available or compatible with Operon.
          Changes to third-party APIs may affect the functionality of certain adapters.
        </Section>

        <Section title="5. Intellectual Property">
          The Operon software, including its design, code, and documentation, is protected by
          intellectual property laws. You may use the Software in accordance with these terms but
          may not reverse engineer, decompile, or create derivative works without authorization.
          <br /><br />
          Code and content generated by AI agents through the Software belong to you, subject to
          the terms of the respective AI provider.
        </Section>

        <Section title="6. Disclaimer of Warranties">
          THE SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. WE DO
          NOT WARRANT THAT THE SOFTWARE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL
          COMPONENTS.
          <br /><br />
          AI-generated code may contain errors, security vulnerabilities, or other issues. You
          acknowledge that AI outputs should always be reviewed before use in any critical or
          production environment.
        </Section>

        <Section title="7. Limitation of Liability">
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT,
          INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE
          SOFTWARE, INCLUDING BUT NOT LIMITED TO:
          <br /><br />
          <List items={[
            'Loss of data, code, or work product.',
            'Costs incurred from third-party API usage.',
            'Damages resulting from AI-generated code.',
            'Service interruptions or API changes.',
          ]} />
        </Section>

        <Section title="8. Modifications">
          We reserve the right to modify the Software and these Terms at any time. Continued use
          of the Software after modifications constitutes acceptance of the updated Terms.
        </Section>

        <Section title="9. Termination">
          You may stop using the Software at any time by uninstalling it from your device. We
          reserve the right to discontinue the Software or any features at any time without prior
          notice.
        </Section>

        <Section title="10. Governing Law">
          These Terms shall be governed by and construed in accordance with applicable laws,
          without regard to conflict of law principles.
        </Section>

        <Section title="11. Contact">
          If you have questions about these Terms, please open an issue on our GitHub repository.
        </Section>
      </div>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 40 }}>
      <h2
        style={{
          fontSize: 20,
          fontWeight: 600,
          color: 'rgba(255,255,255,0.85)',
          marginBottom: 16,
        }}
      >
        {title}
      </h2>
      <div style={{ fontSize: 15, lineHeight: 1.8, color: 'rgba(255,255,255,0.4)', fontWeight: 300 }}>
        {children}
      </div>
    </div>
  )
}

function List({ items }: { items: string[] }) {
  return (
    <ul style={{ margin: 0, paddingLeft: 20 }}>
      {items.map((item, i) => (
        <li key={i} style={{ marginBottom: 6 }}>{item}</li>
      ))}
    </ul>
  )
}
